---
apiVersion: v1
kind: Service
metadata:
  name: nicegui-hello
  namespace: default
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: nicegui-hello
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: <ur ip>

